#!/bin/sh
read -p "Enter Git user e-mail: " email
read -p "Enter Git user name: " name
sudo pacman -S github-cli
git config --global user.email "$email"
git config --global user.name "$name"
git config --global core.editor "vim"

sudo pacman -S  base-devel
cd ~
mkdir aur
cd aur
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -sri

cd ~
mkdir bin
mkdir rclone
mkdir -p github/vinceliuice/grub2-themes
cd github/vinceliuice
git clone https://github.com/vinceliuice/grub2-themes.git

yay -S gnome gdm i3 dmenu i3status rofi gnome-shell-extensions gnome-browser-connector archlinux-wallpaper
yay -S kitty zsh emacs neovim neovim-qt stow man vivaldi rate-mirrors-bin rclone
sudo systemctl enable gdm.service
