#!/bin/sh
read -p "Enter Git user e-mail: " email
read -p "Enter Git user name: " name
sudo pacman -S github-cli
git config --global user.email "$email"
git config --global user.name "$name"
git config --global core.editor "vim"

sudo pacman -S  base-devel
cd ~
mkdir aur
cd aur
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -sri
#sudo pacman -U yay.tar.xz

sudo pacman -S gnome gdm i3 dmenu i3status rofi kitty zsh emacs stow man
sudo systemctl enable gdm.service
