#!/bin/sh
timedatectl set-ntp true
read -p "Enter EFI partition name: " efipart
read -p "Enter system partition name: " systempart
mount /dev/$systempart /mnt
mount --mkdir /dev/$efipart /mnt/boot
pacstrap /mnt base linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab
mkdir /mnt/root/arch-install-scripts
cp * /mnt/root/arch-install-scripts
chmod a+x /mnt/root/arch-install-scripts/config
arch-chroot /mnt /root/arch-install-scripts/config
